apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-tester.fullname" . }}
  labels:
    {{- include "app-tester.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-tester.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        timstamp: "{{ date "20060102150405" .Release.Time }}"
        {{- include "app-tester.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: src-volume
          configMap:
            name: app-tester-src
            defaultMode: 0777
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          workingDir: "/src"
          command: ["./run"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /src
              name: src-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
