apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-tester.fullname" . }}
  labels:
    {{- include "app-tester.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-tester.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        timstamp: "{{ date "20060102150405" .Release.Time }}"
        {{- include "app-tester.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: dist-volume
          configMap:
            name: app-tester-dist
            defaultMode: 0777
        - name: gocache-volume
          hostPath:
            path: /tmp/gocache/
            type: DirectoryOrCreate
        - name: java-volume
          hostPath:
            path: /tmp/java/
            type: DirectoryOrCreate
        - name: mvn-volume
          hostPath:
            path: /tmp/.m2/
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          workingDir: "/"
          command: ["/bin/sh", "-c"]
          args: ["tar -zxvf dist.tar.gz && cd /dist && ./run"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            failureThreshold: 20 
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOCACHE
              value: /tmp/gocache
          volumeMounts:
            - mountPath: /dist.tar.gz
              name: dist-volume
              subPath: dist.tar.gz
            - mountPath: /tmp/gocache/
              name: gocache-volume
            - mountPath: /root/.m2/
              name: mvn-volume
            - mountPath: /tmp/java/
              name: java-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
