# Default values for app-tester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image: golang:latest

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
